### ISSUE TITLE
Add support for redirects when rendering a page

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#10]
As we now index redirects properly, the middleware for resolving URLs can support redirects by responding with ... a redirect.

**Comment by thomasegense** [comment]
Awaiting response from curators about wanted behavior...

**Comment by thomasegense** [comment]
Solved. Sometimes a redirect will be returned to the browser.
When possible I will just serve the correct resource without having the browser go through the redirect. (in the downloadRaw method for images and other binaries etc.)
