### ISSUE TITLE
Warn about non-bracketed boolean operators

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#107]
If the user enters a query such as `computer AND apple OR amiga` then the behavior is not obvious. In that case the GUI should state this and recommend adding clarifying parentheses.

Proper parsing to detect ambiguous queries is not trivial, but a simple fuzzy logic such as _the query contains both AND and OR but no parentheses_ to trigger the warning would be a nice start.

If a proper parsing is wanted, one way would be to use the Lucene query parser to perform an abstract parsing of the query, then drill down into the produced tree and look for [BooleanQuery](https://lucene.apache.org/core/3_0_3/api/core/org/apache/lucene/search/BooleanQuery.html) with a mix of [Occur.MUST](https://lucene.apache.org/core/3_0_3/api/core/org/apache/lucene/search/BooleanClause.Occur.html) and SHOULD.

**Comment by jorntx** [comment]
@thomasegense should we transfer this to the internal jira?

**Comment by thomasegense** [comment]
No, closing it.. I saw the query parser from summa, dont want to go there....
We are already warning about it in the search help guidelines.
