### ISSUE TITLE
After searching show both hits and group hits

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#12]
Etc. a search will result in 600 documents, but due to grouping the real result is 1200 documents, but only the 600 are returned.  It would be informative to show both hitcounts.
Ask Toke for an idea to present both counts.
The two hitcounts can be seen below in the response from solr.
grouped.matches and  group.url.doclist.numFound

"grouped":{
    "url":{
      "matches":1239,
      "doclist":{"numFound":661,"start":0,"maxScore":118.411,"docs":[

**Comment by NielsGamborg** [comment]
Now showing both hitcounts with a tooltip to explain the differnece. Fixed on the "group_fix" branch.
