### ISSUE TITLE
please implement link graph

### ISSUE THREAD

**Issue by vitezg** [netarchivesuite/solrwayback#130]
The link graph in the current release seems to be unimplemented yet. Opening this ticket as we already have links on our public website to the link-graph URLs of the previous version of solrwayback.

**Comment by thomasegense** [comment]
Yes, we are aware of that, it was in the change notes. 
Good news is that it will be reimplemented next week and just require a new WAR-file.

**Comment by thomasegense** [comment]
I did a fast backport of the linkgraph.jsp. It seems to work, though the rest of the frontend is pure javascript and not JSP.
But it is important for me to know if you are using a deep link to the link-graph from another site? 
Then we need also implement a handler for catch this when reimplemening the page.

He is the backport with old linkgraph jsp:
https://drive.google.com/file/d/1t5uNNtZ5obUbx2GCOJlW35zexj-4YdRD/view?usp=sharing

Use it if you cant wait 2 weeks :)

**Comment by vitezg** [comment]
Thanks a lot, will test it. Yes we do have deep links from this page: https://webarchivum.oszk.hu/en/webarchive/sub-collections/demo-archive/

**Comment by thomasegense** [comment]
It is under development right now. Link to it will probably change in the new version - (.jsp) will be removed from link. 
I  guess that will be easy for you to change the link from the overview page?

**Comment by vitezg** [comment]
Great news, thanks Thomas! Yes, it will be easy to change the links.

**Comment by thomasegense** [comment]
Closing, has been fixed. the new url for the stand-alone linkgraph component is: 
/solrwayback/linkgraph?domain=kb.dk
