### ISSUE TITLE
The image boxes scale but the images doesn't

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#137]
The yellow image boxes are relative to browser width, but the images in the boxes are fixed width. This results in images flowing outside of the boxes and overlapping images if the browser is not wide enough.

**Comment by jesperlauridsen** [comment]
@tokee this should be fixed in branch ISSUE-137-image-scale-not-working-correctly - go check it out if you're satisfied. Or get @jorntx  to check it out for you if you're to lazy to have the devel intance running on your machine ;-)

**Comment by thomasegense** [comment]
@tokee  Is this fixed by Jesper now ?

**Comment by thomasegense** [comment]
@tokee

**Comment by tokee** [comment]
It is fixed in master now. Don't know when that happened.

**Comment by jorntx** [comment]
Sounds good!
