### ISSUE TITLE
Support heatmaps for geo search

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#14]
The current geo search for images is limited in scale (500 images max) for performance reasons. If the purpose is to find concentrations of images rather than individual images, heatmaps can be used instead as they work on the full result set: https://lucene.apache.org/solr/guide/7_3/spatial-search.html#heatmap-faceting

**Comment by thomasegense** [comment]
Think this is more a specific research goal than normal user interaction. And can be done with an export and then custom parsing of the coordinates.

**Comment by thomasegense** [comment]
The new Geo search has local heatmaps for the area and with the new lazy load of image I think we can scale well over 500. It is solr that takes all the time now and even with 500 there is 30+ seconds wait.
