### ISSUE TITLE
Save web page as WARC

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#16]
With the existing code for re-mapping webpage resource URLs as well as exporting af WARC, it seems simple to add a "Download webpage as WARC" functionality to the webpage render overlay.

Further refinement: "Download all instances of webpage as WARC" to get all historical versions.

Implementation idea: Create an extended export function with an optional `includeEmbeddedResources` flag that extracts all resource-links from webpages in the export set and adds them to the set. This would make the two ideas above trivial as they would just be a call with a suitable constructed query (`url"..." AND crawl_date:"..."` for the first and simply `url=`...` for the second). The extended export functionality could also be exposed to the general download GUI, making it possible to get a "full" dump for a given query.

**Comment by thomasegense** [comment]
There is already enough export options. And you can do this with current interface if you are a little smart.
Just search for the id etc. : id:"H21r2lR1tbN9t/EYEKOLEw==/20001128112039"
This will give 1 result and you can then export it to warc (with resources).
