### ISSUE TITLE
SolrWayback should expose the CDX-API

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#169]
We have all the information, why not let SolrWayback act as a [CDX-server](https://github.com/webrecorder/pywb/wiki/CDX-Server-API), så that there is not a need for a separate index? (suggested by Yves Maurer at a webinar)

**Comment by thomasegense** [comment]
I will close this. To put it short, noone will benefit from it.

It will not improve playback by using PyWb instead  of SolrWayback by exposing a primitive CDX-server that PyWB can call.
As long prefix search and POST requests can not be handled with the currect version of WARC-Indexer+Solr, there will be no 
playback (or very little) playback improvement. Also old WARC-files harvested with Heritrix does save the post-data in the request.

Use Outback-CDX + PyWb to have playback work for the most complated SOME sites such as Facebook. This also require the harvest was done with WebRecorder technology.
