### ISSUE TITLE
Similar project: Bookmark Archiver

### ISSUE THREAD

**Issue by pirate** [netarchivesuite/solrwayback#17]
I added [ElasticLunr.js](http://elasticlunr.com/) search support to my WARC/DOM/PDF saving web archiving tool recently: [Bookmark Archiver](https://github.com/pirate/bookmark-archiver).

In the process of doing research for that, I discovered this project, and am pleasantly surprised to see a lot of overlap between our goals and feature-sets.  Your UI is definitely nicer than mine, and you guys have some really cool features that I may end up taking inspiration from.

Anyway, just wanted to say hi, and good luck on your development, you're welcome to re-use any code from my project if it helps in any way.

**Comment by tokee** [comment]
Thanks for the greeting & heads up, @pirate. [Bookmark Archiver](https://github.com/pirate/bookmark-archiver) looks very interesting. I like the no holds barred approach to archiving the pages and I will be evaluating your tool for personal use.

SolrWayback is very much a server-based tool and as such it is vulnerable to time as it does require running upgrades to Tomcat & Solr to stay ahead of security issues. So the extra functionality does come at a price. While the static content from Bookmark Archiver might be more limited, the "works forever"-part is great.
