### ISSUE TITLE
Minor GUI issues in Chrome

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#186]
The following issues is Chrome/Chromium only. It looks good in firefox.

1)The arrow icon for more results under domain facet is not load correct. Shows a weird character
2)When showing a result set, the "See available export options" is cut and missing chrome

**Comment by jorntx** [comment]
In order to fix this I need OS type and version as well as browser version.

I cannot reproduce in OSX 11.2.3 (20D91)  - Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Comment by thomasegense** [comment]
I can also not reproduce (on laptop). Will check again tomorrow from work.

**Comment by thomasegense** [comment]
Can not reproduce
