### ISSUE TITLE
Add check for wget in warc-indexer.sh

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#195]
The `warc-indexer.sh`-script assumes that `wget` is installed for both verification of Solr collection existence and for flushing. Those fail poorly if `wget` is not there.

There should be a check for `wget` and a proper warning that the two actions could not be performed if `wget` is not available..

**Comment by tokee** [comment]
This will be handled in #352 by switching to `curl` which is more readily available.

**Comment by thomasegense** [comment]
Fixed
