### ISSUE TITLE
Switch to String based Tweet-IDs

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#197]
When https://github.com/netarchivesuite/webarchive-discovery/issues/11 has been implemented, SolrWayback must be updated to use String based IDs.

Ping to @Bohlski

**Comment by thomasegense** [comment]
@Bohlski  This will probably not need code changes in SolrWayback. But you need a new schema.xml for Solr, a new warc-indexer. And then you have to index again.

**Comment by tokee** [comment]
Closed by 8e4f116a67482a40b4b9b569fd1d4eeaf5c25a64 by simply changing `tw_tweet_id` and `tw_reply_to_tweet_id` in `schema.xml` from `long` to `string`.

A complete re-index for existing collections is needed, but it does not require any changes to SolrWayback.
