### ISSUE TITLE
Some mp4 video's not playing from result list

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#201]
This is due to a Tika bug. The video is identified as content_type: 'application/mp4' and this is a not a valid type.

Solution fix:
If this content_type is found rewrite it to 'video/mp4' for the media player.

For some reason this does not happen to all MP4 videos.

**Comment by jorntx** [comment]
First try at fix here - https://github.com/netarchivesuite/solrwayback/pull/202

**Comment by thomasegense** [comment]
It worked :)
