### ISSUE TITLE
Content disappears after load

### ISSUE THREAD

**Issue by thsm-kb** [netarchivesuite/solrwayback#204]
https://solrwb-stage.kb.dk:4000/solrwayback/services/web/20210330100306/https://www.paqle.dk/p/marie-krarup/113194

Content appears briefly while loading, but is then hidden.
No problem when testing with javascript turned off. 

https://sbprojects.statsbiblioteket.dk/jira/browse/NETH-624

Maybe similar issue with zetland.dk

**Comment by thomasegense** [comment]
Use internal boards for these playback issues.  Looks like one of those unfixable playback errors unless you use Outback CDX/PyWb. 

POST requests that break playback is not something that can be fixed. It involves a lot of cheating and a contract between playback and Outback CDX to fix it.
