### ISSUE TITLE
Add support for stats

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#218]
The [Solr stats component](https://solr.apache.org/guide/8_11/the-stats-component.html) delivers statistics, primarily for numeric fields, such as average, count and sum. It is benign in its default state, meaning that it does not have excessive memory overhead. Extra features such as `cardinality` are a bit dangerous and the `distinctValues` & `countDistinct` will result in Out Of Memory for some fields.

SolrWayback should add support for calling the stats component in a controlled manner, meaning that only fields & features specified in the setup should be allowed.

**Comment by VictorHarbo** [comment]
I would like to take a look at implementing this.

**Comment by VictorHarbo** [comment]
#330 implements the Solr Stats component in the java layer. To fully implement this functionality these functions have to be called and used by the frontend. 

Some following steps:

- Create java facade for `SolrStats`.
- Figure out where to call this in the frontend

**Comment by VictorHarbo** [comment]
With #339 merged this issue is down to one unresolved feature: How to implement the stats component in the frontend. 

Stats queries can have a heavy load time, which needs to be communicated to the end-users in a meaningful way.

**Comment by jesperlauridsen** [comment]
If we already have a open issue for this #343, can we safely close this one, @VictorHarbo?

**Comment by VictorHarbo** [comment]
Yes! Indeed we can! If you feel like it and have the time, you are welcome to have a look at #343.

**Comment by VictorHarbo** [comment]
Closing the issue as the backend part of the stats component has been implemented and the frontend has its own issue: #343
