### ISSUE TITLE
Routing bug (local only?) introduced in PR #219

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#224]
How to reproduce:
Running SolrWayback on localhost and open url:
http://localhost:8080/solrwayback/search?query=type%3A%22Web%20Page%22&grouping=false&imgSearch=false&offset=0&urlSearch=false&facets=
This will work. But pressing "Next 20" will give an error because the new url is
http://localhost:8080/solrwayback/search/search?query=.... 
Notice "**search**" is double in the URL.
There bug also gives problem in Twitter Playback as an extra / is added to /search/.

The bugs seems to have been introduced in patch:
https://github.com/netarchivesuite/solrwayback/pull/219
Reverting 'router/index.js' and 'vue.config.js' and the bug disappears.

Maybe @anjackson  has an idea what goes wrong?

**Comment by thomasegense** [comment]
I have reverted the files on master. They were also causing the toolbox to generate non existing links.

**Comment by jorntx** [comment]
Thanks for reporting @thomasegense and reverting is the thing to do for now until I have the time to debug the issue.

**Comment by thomasegense** [comment]
Included in release 3.5.0
