### ISSUE TITLE
URL-search does not handle parameters well

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#232]
Reported by Sara Aubry, https://www.bnf.fr/fr https://webcorpora.hypotheses.org/

URL SEARCH for SolrWayback takes an URL such as `http://www.example.com/forums/showpost.php?p=32095&postcount=40` and creates the query `url_norm:"http://example.com/forums/showpost.php?p=32095"` which does not match anything. A search for `url:"http://www.example.com/forums/showpost.php?p=32095&postcount=40"` does work: Notice that is is `url`, not `url_norm` and including the `postcount` parameter.

Something's off here: Maybe the normaliser for `url_norm`-search does not match the indexing normaliser? Or maybe it would be better to perform a search for `url_norm:normaliser_url OR url:original_url`?

**Comment by bnfleb** [comment]
The problem comes from the call to `"/util/normalizeurl"` : Solrwayback use a GET request so the parameter is lost.
Using a POST request will fix the bug.

**Comment by thomasegense** [comment]
Confirmed. The frontend should url-encode  the parameter or method should be changed to POST which will also fix the problem. 
Assigned to @jorntx and he can decide which solution we take.

**Comment by thomasegense** [comment]
This PR has been merged into master now.
