### ISSUE TITLE
pass GUI update to the package and deploy

### ISSUE THREAD

**Issue by mw0000** [netarchivesuite/solrwayback#234]
Hi,

I have made some changes to the GUI and generated `/dist` as it is in any Vue application. I've generated a package by using `mvn package`. Can you point the way in which I can deploy this changes to the server? I've previously install and now using SolrWayback software bundle.

**Comment by thomasegense** [comment]
@jorntx Is frontender and can answer.

But I suggest you just download the bundle install and just redeploy the WAR-file
1) mvn clean package -DskipTest
2)rename thesolrwayback-4.3.1-SNAPSHOT.war to solrwayback.war
3) copy solrwayback.war into the tomcat/webapps folder.

If you make a small script for this, then the turn around time will only be 30 seconds.

script example here:

```

#!/bin/sh

deployFolder='/media/teg/1200GB_SSD/solrwayback_package_4.3.0/apache-tomcat-8.5.60/webapps'

rm -r $deployFolder/solrwayback 
mvn clean package -DskipTests
mv target/solrwayback*.war target/solrwayback.war
cp target/solrwayback.war $deployFolder

echo "solrwayback deployed to localtomcat"
```

**Comment by mw0000** [comment]
I works :) Thank you!

**Comment by jorntx** [comment]
For future reference - no need to build the frontend separately - this is all done by the Maven (mvn) 'package' command:)

**Comment by thomasegense** [comment]
And closing... 3.. 2... 1
