### ISSUE TITLE
make the pwid configurable via a Java property

### ISSUE THREAD

**Issue by vitezg** [netarchivesuite/solrwayback#24]
The pwid seems to be hardcoded as netarkivet.dk , for example http://193.6.201.202/solrwayback/services/generatepwid?source_file_path=/var/local/wct/wayback/store/WEB-20180123104243008-00000-12662~webadmin.oszk.hu~8443.ver1.warc.gz&offset=59972733 . Please make it configurable with Java property.

**Comment by thomasegense** [comment]
Fixed in  version_3_2_branch.
