### ISSUE TITLE
url_search is called twice from the frontend

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#257]
Check network console in browser and start and url-search.

The same service method that normalize is called twice.

**Comment by jorntx** [comment]
Not a bug per se - what happens is that the first call is for search and second call is for facets. I admit that the logic could be a little leaner - with one call to normalize-url and then a call to normal and facet search. This would require a refactor. Does the double call to normalize-url have a huge performance impact?

**Comment by thomasegense** [comment]
Impact is very minimal. But there are no search-result or facets here. 
When the url_norm has been returned  then  it can trigger a search which will be two calls.

**Comment by thomasegense** [comment]
Closing for now. No  quick-fix and users do not see it anyway

**Comment by jorntx** [comment]
Fixed
