### ISSUE TITLE
image resizing does not work with openjdk

### ISSUE THREAD

**Issue by vitezg** [netarchivesuite/solrwayback#26]
The /services/image endpoint throws this exception with OpenJDK:
` javax.imageio.IIOException: Invalid argument to native writeImage`

Changing line 331 in SolrWaybackResource.java from this:
`  @Produces("image/jpeg")`
to this:
`  @Produces("image/png")`
fixes the issue.

This seems to be an openjdk specific bug: https://stackoverflow.com/questions/3432388/imageio-not-able-to-write-a-jpeg-file
However changing the output image type in ImageUtils.java line 25 to TYPE_3BYTE_BGR from TYPE_INT_RGB does not fix this issue.

**Comment by thomasegense** [comment]
Thank you. I think I have seen this error several times but did not have the time to follow it up.
I will fix this this on the version 3.2 branch after some testing.
Will close when I have comitted it.

**Comment by thomasegense** [comment]
Could not find an image that could reproduce the error, but I changed it and everything seems to work fine. There is no reason it should be an jpeg image, when all other images generated by solrwayback is png.

**Comment by thomasegense** [comment]
(fixed on version_3_2_branch)
