### ISSUE TITLE
please move the property file into the webapp's directory

### ISSUE THREAD

**Issue by vitezg** [netarchivesuite/solrwayback#27]
Currently solrwayback's property file is located in the home directory of the J2EE server. This makes it hard to test new versions as new instances because they all share the configuration. Please move the property file to the solrwayback webapp's directory to avoid this issue.

**Comment by thomasegense** [comment]
I made a more intermediate solution that I hope you can accept. 
In your case it will look for a property-file called solrwayback32.properties in the home-dir first, before defaulting to solrwayback.properties if the file does not exists.
---
Commit message:
You can now use a context specific solrwayback.property file.
If the webbapp is not deployed under "solrwayback", but solrwayback32 etc. Then it will first look for a propertyfile (in home-dir) called solrwayback32.properties. If it does not exist it will default the solrwayback.properties file. That way you can have multiple solrwayback instances deployed under different context roots and each can have its own propertyfile.

**Comment by thomasegense** [comment]
@vitezg  You can close the issue it if you can accept this solution.

**Comment by vitezg** [comment]
solution accepted, thanks!
