### ISSUE TITLE
Refine time frame and time scale on "Visualization of search result by domain"

### ISSUE THREAD

**Issue by saraaubry** [netarchivesuite/solrwayback#270]
Currently, the "Visualization of search result by domain" graph is distributed by year (1998-2022). The display is not useful when using SorlWayback with a smaller collection. In our case, the collection ranges from march to june 2022.

BnF suggests an evolution to give users the possiblity to refine :
- the time frame using 2 dates defined as YYYY-MM-DD -> YYYY-MM-DD.
- the time scale (with a choice between year, month, week, day)

Defaults value are : 
- date 1 : defined setting for the beginning of the archive (1998-01-01)
- date 2 : today
- time scale : year
which do not change current implementation.

![visu-search-results](https://user-images.githubusercontent.com/6735961/196646874-73e95e88-0249-4c97-89ce-ff7c4288e9b9.PNG)

**Comment by thomasegense** [comment]
That is a very good idea for the GUI! 
Right now you can only configure the start year in the solrwaybackweb.properties. The default is 1998. 
But for newer collections using months as buckets makes a lot more sense and you are not the first to suggest this.

I will make this issue high priority and hope we can implement it soon.

The minor details is we do not have year-month is not in the index. The current implementation uses crawl_year. And it took two optimizations each giving a factor 10, to make it perform as it is now.  So performance may be a lot worse when using months as buckets. But for large and old collections you probably do not want to use months anyway. And newer collections are much smaller so performance might not be an issue. The date field crawl_date can maybe be used for this.

I hope @tokee  can find a way to make Solr give this dataformat. I will do the implementation.

**Comment by bnfleb** [comment]
I already implement the Solr query using the field crawl_date:
`q=*:*&rows=0&facet=false
&json.facet={
    domains:{
        type:terms,
        field:domain,
        limit:30,
        facet:{
            years:{
                type:range,
                field:crawl_date,
                start:'2002-01-01T00:00:00Z',
                end:'2003-01-01T00:00:00Z',
                gap:'+1MONTH'
                }
            }
        }
    }`

I need a little time for the GUI but the PR will come soon

**Comment by thomasegense** [comment]
@tokee  I will try the query tomorrow. Starting with a smaller year range. But I think you could be right that some validation of input can be required. Maybe depending on total number docs?

**Comment by thomasegense** [comment]
@bnfleb  @tokee  I did some performance testing with the gap size DAY or MONTH. The test was against our full corpus (40B documents)

Notice WEEK does not seems to be an gap parameter option. There is only DAY, MONTH,YEAR.  (Can you confirm?)
Here are my results. I tried to avoid filter caching by changing query and range between each search.
Here hits is the total number of hits for that query ( with no time restriction.)

| GAP  | #hits   | Query time in millis   |
|---|---|---|
|30 days|    436117371| 10969|
|30 days     262183283|   4625|
|30 days|    14539  |1542|
|30 days|    35949582  |43529|
|30 days|     41782615454(*:*)|      21388|
|30 days|     169054701|         |13375|
|365 days|  19257591| 518339|
|12 months|   3257610797 | 20306|
|12 months|   41782615454 (*:*)  | 20839  |
|12 months|   158417189 |6697|
|12 months|   550322862| 9022|
|24 months|   105942008  | 14856|
|36 months| 101033702| 467252|
|36 months|   43498881| 477063|
|60 months|   45127150 |  497424 |
|60 months|   1109480663|    501362|
|120 months  | 33796016     | 522942|
|120 months |1081048  527100|
|252 months|  14359 |278320| 
|252 months|  55529 | 68426|

Conclusion: The performance seems to scale roughly with 
`time = O(#total hits * buckets`)

As I see it limiting to 36 buckets maximum is a good value. This can show a whole month, or the whole collection by year, or 3 years by month. 

I doubt the performance can be tweaked by changing the query in any way. A future option would be a new field  'index_month' YYYYMM in the schema. But I can not even sure it would improve that much.



|

**Comment by thomasegense** [comment]
Fixed and merged to master.

Also domain statistics in the toolbar has been improved with identical time frames .
