### ISSUE TITLE
Multiple alternative playback engines

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#274]
It seems like a common case to have a local [pywb](https://pypi.org/project/pywb/) instance as an alternative playback engine and also to use [archive.org](https://archive.org/) as fallback.

SolrWayback should support multiple alternative playback engines.

This ties neatly with #275 as that issue also requires changes to the configuration format.

**Comment by thomasegense** [comment]
Work in progress. Awaiting code review of PR + test approval from Volodymyr.

**Comment by thomasegense** [comment]
Fixed. Can use template with {$collection}  or {$collection_id} in solrwaybackweb.properties. 
Can also have individual hardcoded urls for each collection (multiple values in property)
