### ISSUE TITLE
Frontend switch to new method for CSV export

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#279]
The new method is: '/export/fields'

See last message for updated information.

**Comment by jorntx** [comment]
Which PR er you referring to and will you fix this?

**Comment by thomasegense** [comment]
@jorntx  Hope you can implement this when the large PR has been accepted. I will make a more detailed of the
new parameters the backend can take.

**Comment by jorntx** [comment]
Can you tag the PR referred to in this issue so I can track its status?

**Comment by thomasegense** [comment]
The monster PR has been merged.  

API:
  @Path("/export/fields")
  public Response exportFields(@QueryParam("query") String q, @QueryParam("fq") String fq,
                               @QueryParam("fields") String fields,
                               @QueryParam("expandResources") Boolean expandResources,
                               @QueryParam("ensureUnique") Boolean ensureUnique,
                               @QueryParam("groupfield") String groupField,
                               @QueryParam("flatten") Boolean flatten,
                               @QueryParam("format") String format,
                               @QueryParam("gzip") Boolean gzip) throws SolrWaybackServiceException {

The GUI needs option to pick one of the 3 format types. (dropdown maybe)
csv,json jsonl  and an icon(?) with hard-coded mouseover text. 

The GUI needs option (checkbox) for flatten and an icon(?) with hard-coded mouseover text. 
The GUI needs option (checkbox) for GZIP and an icon(?) with hard-coded mouseover text. 

if grouping is selected in the query, you need to set this the value 'url'. If not, do not set it.
ensureUnique should not be set.

**Comment by thomasegense** [comment]
Mouseover  grouping: Documents will be grouped on the given field and only the first document will be exported in each group
Mouseover flatten: Flatten will split multivalue fields into single values and add as many new lines to the export. Using with 'content' field selected can cause very large exports.

**Comment by thomasegense** [comment]
Is fixed. The missing part of group dropdown for query is created in a new PR.
