### ISSUE TITLE
switch to leaflet.js from the google maps api

### ISSUE THREAD

**Issue by vitezg** [netarchivesuite/solrwayback#28]
https://leafletjs.com/ supports multiple map backends, including google maps and openstreetmap. This way solrwayback would not be tied to the google ecosystem.

**Comment by thomasegense** [comment]
This will not make it for the 3.2 release unfortunately. My frontend skills in the VUE framework needs to be updated a bit first and I have other priorities as well :( 
@vitezg you welcome to clone the 3.2 release branch and implement it yourself :) I will accept the merge request of course.

**Comment by thomasegense** [comment]
Closed
