### ISSUE TITLE
Applied Facets: you can select the same facet several times

### ISSUE THREAD

**Issue by Klindten** [netarchivesuite/solrwayback#298]
Task: Shouldn't it be checked if a facet was already selected so that the list doesn't just continue if you select the same facet several times?
![image](https://user-images.githubusercontent.com/74599011/205067385-d693d656-b0de-4bb4-a2a1-d55ba7267107.png)

**Comment by thomasegense** [comment]
Assigned to @jorntx .
I do not know if this is an easy fix.

**Comment by jesperlauridsen** [comment]
Merged into master, closing the issue. Will be in the next release.
