### ISSUE TITLE
Html_site_Title_tag is shown in CAPITAL for search result in SolrWayback

### ISSUE THREAD

**Issue by Klindten** [netarchivesuite/solrwayback#299]
Maybe the appearance in solrWayback should follow the HTML....

![Html_site_Title_tag_](https://user-images.githubusercontent.com/74599011/205069239-b0392d63-3881-4943-a28a-591bafeafc08.png)
![Html_site_Title_tag_Capital_SolrWayback](https://user-images.githubusercontent.com/74599011/205069240-fe12e176-1482-4c19-a113-2c44e45b2f69.PNG)

**Comment by thomasegense** [comment]
I agree, there is no reason to upper case the title.

Assigned to @jorntx

**Comment by jorntx** [comment]
Linked PR
