### ISSUE TITLE
Better proxy support by leveraging referrer

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#3]
The current proxy works from a whitelist of hosts. If the requested resource is not on the list, it is not served. This means that resources referred from a page (embedded images, JavaScript, CSS et al) are only served if they are caught by the URL-rewriter in SolrWayback.

The proxy could be extended to look at the request headers for resources with URLs where the host is not the SolrWayback-machine. If the request has the referrer-header set to the original request to the SolrWayback server, then the wanted timestamp can be extracted and the resource can be resolved from the archive, instead of being blocked.

Additional idea: Instead of just delivering the resource, Solrwayback could send a redirect message to a Solrwayback-lookup with the inferred timestamp. This would ensure that multiple chained lookups (e.g. JavaScripts including other JavaScripts) would also work.

**Comment by thomasegense** [comment]
Implemented!
Some leak fixes will work without proxy mode. So this is better playback with no effort for users.
To fix live leaks and not just block them, you can optional install the root webapplication:
https://github.com/netarchivesuite/solrwaybackrootproxy

It needs to be renamed to ROOT.war for tomcat. It will be part of the version 3.2 SolrWayback Bundle release.

The technical details are horrifying and fixes 5 different types of leaks.
All of them uses the referer-url from the header information.
