### ISSUE TITLE
Can/should the search field be slightly wider, so that it aligns with the content on the page to the right

### ISSUE THREAD

**Issue by Klindten** [netarchivesuite/solrwayback#300]
![image](https://user-images.githubusercontent.com/74599011/205069823-f28e4355-c78f-4a42-8141-837c4ac6fd4d.png)

**Comment by thomasegense** [comment]
Very good idea. I think it has shrunk somehow, I remember to made it longer once. Maybe by introduction of logo to the left.

**Comment by thomasegense** [comment]
Assigned to @jorntx 
Think this is an easy fix.

It is a regression error after the logo in the top left corner was introduced.

**Comment by jorntx** [comment]
Made a small adjustment on wide screens (linked PR)  - it is not perfect but agreed with @thomasegense that it is good enough for now - given our limited time frame
