### ISSUE TITLE
Loader/spinner at NGram search looks different than the others 

### ISSUE THREAD

**Issue by Klindten** [netarchivesuite/solrwayback#301]
Seems like two files on top of each other.

TOOLBOX>Ngram search>make a search
https://watch.screencastify.com/v/nzUX33mCV0ov2WI43tR4

**Comment by thomasegense** [comment]
Also spinner loads forever if server returns as http 500 message.

If a http 400 is returned, it stops correct and show the error message.

**Comment by jorntx** [comment]
Merged to master
