### ISSUE TITLE
Option for query to be non-case sensitive

### ISSUE THREAD

**Issue by Klindten** [netarchivesuite/solrwayback#306]
When searching for specific collections/WARC-names/URL´s it could be great to have a tick box or similiar to toggle case-sensitivity. 

Example in the Danish Webarchive:

arc_full:*webrec_folk* will give you all results but 
arc_full:*webrec_Folk* will give no results.

The point being that users might use capital-letters for nouns/names even though this is not in our naming guides.

**Comment by thomasegense** [comment]
In the linux file system it will be two different files if they both exist. And the internal workings in solrwayback performs this query also. If it would return two different results it may break playback etc.

A solution would be a virtual field alias (new field) for arc_full that searches case insensitive. But this will  increase the index size (a little) and also require a full reindexing. Users that search by arc_full are expert users and they should know this. And it comes with a cost that users now has to understand the difference between these.

I am closing the issue. Too much work for very little benefit. And it can not be solved in the Danish Netarchive for many years until we reindex everything again.
