### ISSUE TITLE
Wrong word in search syntax guidelines

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#309]
When clicking on the `?` to the right of the query box, the search syntax guidelines states

> **Use brackets if mixing operators**
> To avoid ambiguous interpretation of syntax always use brackets () if mixing operators.
> Example: (computer AND apple) OR (amiga)
> This can also return results where only the text 'amiga' is found. 

Those are not **brackets** but **parentheses**

**Comment by thomasegense** [comment]
Fixed.
