### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by ibnesayeed** [netarchivesuite/solrwayback#32]
Currently used `docker-run.sh` approach requires users to have Maven installed on the host machine where the container is supposed to run. A more practical approach to better utilize Docker toolsets would be to create a multi-stage Dockerfile and build an image with necessary artifacts built and packaged in it. A good example can be found in the OWB repo at https://github.com/iipc/openwayback/blob/master/Dockerfile.

**Comment by ibnesayeed** [comment]
If and when a PR is ready, I can review it and provide feedback.

**Comment by tokee** [comment]
It is now 2023 and saying "We don't do Docker" is quite a statement. I am reopening this issue so that we remember to rediscuss whether we should have a docker image for running the SolrWayback + indexer + Solr stack.

**Comment by thomasegense** [comment]
And we now have a docker file that is very easy to use and you can index warc-files from a folder outside the container.
