### ISSUE TITLE
Better error message for FileMovedMappingResolver

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#373]
As https://github.com/netarchivesuite/solrwayback/issues/2#issuecomment-1584379873 shows, specifying a folder instead of a file for `FileMovedMappingResolver` leads to a poor error message and SolrWayback exiting. The exit part is fine, but the error messaging should be improved.

**Comment by thomasegense** [comment]
Fixed. Also with the new solrwayback_error.log from version-4.4.2 it is much easier to find errors.
