### ISSUE TITLE
Improve FileMovedMappingResolver with auto discovery

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#374]
Maintaining a mapping file for `FileMovedMappingResolver` is tedious. It should have an auto discovery feature, where one or more root folders for WARCs listed in the configuration are scanned upon startup as well as re-scanned at stated intervals. Or maybe re-scans should be triggered when a WARC cannot be located?

**Comment by thomasegense** [comment]
Added error log message. With the new solrwayback_error.log, it is very easy to find important error messages.
