### ISSUE TITLE
Implement CDXJ-export

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#388]
As preparation for #360 a [CDXJ](https://pywb.readthedocs.io/en/latest/manual/indexing.html#cdxj-index) exporter should be implemented. With the possible exception of `length`, the fields should all be available in the index and the new functionality is basically a CSV export, mapped to the CDXJ format.

It is unclear to me (Toke Eskildsen) if the `length` field refers to the length of the binary data delivered by a request or if it refers to the length of the (typically) gzip compressed block in the WARC file. If it is the latter, the index produced by the webarchive-discovery project, and therefore also by SolrWayback bundle, does not have this field.

**Comment by thomasegense** [comment]
Just to make it clear that the indexer would never be able to support the --post-append option, so any playback in PyWB would not be improved.

**Comment by thomasegense** [comment]
Closing this issue.  Instead of extracting CDXJ and then index it into a CDX-server. It is better to implement the CDX server API
and avoid the middle step.(CDX-index would never support --post-append.)
