### ISSUE TITLE
Adding "warc_key_id" as default field for export of query result

### ISSUE THREAD

**Issue by joncto** [netarchivesuite/solrwayback#392]
When exporting query results to CSV/JSON/JSONL, I found adding information about the archival resources's urn very helpful. In **solrwaybackweb.properties**, I added `warc_key_id` to the many fields allowed by `export.csv.fields`, but maybe it could be listed there by default?

**Comment by thomasegense** [comment]
@joncto  Thanks, must have been an oversight.

Is added now to the master branch.

**Comment by joncto** [comment]
As always, our response time is impeccable @thomasegense !

(Not sure if you want new issues for all sorts of small details, so just a tiny comment related to this:
Since the "Export CSV" functionality also allows other formats - for further computation, one might prefer JSON/JSONL - would it make sense to rename it in a future release? E.g. "Export query result", "Export derivatives", or similar? Not an urgent matter, but it could be instructive for the end-user, not implying CSV as the natural choice.)

**Comment by thomasegense** [comment]
@joncto  The text has been corrected in the GUI dropdown now.
The propertyname i solrwaybackweb.properties still has the name 'export.csv.fields'. But I made a comment about the property that is also covers JSON/JSONL. Changing the name of the property will require users also has to change it when upgradring.
For next major release  version, the property names can be changed.
