### ISSUE TITLE
SolrUtils.combineFilterQueries combines wrong

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#395]
`SolrUtils.combineFilterQueries` combines using ` AND `, which leads to changed filter behaviour us the input is e.g. `foo:bar OR bar:zoom` and `boom:moo`, which becomes `(foo:bar OR bar:zoom AND boom:moo)`, where it should have been `(foo:bar OR bar:zoom) AND (boom:moo)`. The last parentheses pair is not needed but also does not hurt.

Replacing
```
    .collect(Collectors.joining(" AND ", "(", ")"));
```
with
```
    .collect(Collectors.joining(") AND (", "(", ")"));
```
should fix it.

**Comment by thomasegense** [comment]
Unitttest unittest!

**Comment by VictorHarbo** [comment]
> Unitttest unittest!

Indeed! I'd even created a class for testing and written a test in which i found quite a flaw: It didn't act as a unittest, because i forgot the assertion. That will be fixed as well.
