### ISSUE TITLE
Add custom exports

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#40]
We have encountered the need for exporting specific fields several times. The current GUI has a few pre-selected export possibilities. We should add a custom option, where the user is presented with a list of all exportable fields (this list can be created using the [schema-API](https://lucene.apache.org/solr/guide/7_5/schema-api.html). The user selects the needed fields and the export starts.

Bonus: Also select output format: `csv`, `xml` or `json`, with the option of exporting JSON as one giant valid JSON or the more usable one-JSON-line-per-document.

**Comment by thomasegense** [comment]
Created as internal jira. (custom fields, not the JSON part)

**Comment by thomasegense** [comment]
Will be in the 4.0.0 release (new frontend rewrite). Only CVS format.
