### ISSUE TITLE
Fix mvn jetty:run

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#401]
Running `mvn jetty:run` does not work. There is no outright error and the log seems fine, but the SolrWayback GUI is not available.

**Comment by VictorHarbo** [comment]
I've just tried to recreate this on my MacBookm with no luck, which might be a good thing. I recall that Toke and I both had the problem on our linux machines. I'll test it there as well and if it runs I'll close the issue.

**Comment by thomasegense** [comment]
This will be fixed in PR  #465 
Development Jetty server replaced by Tomcat9 server using cargo plugin. Routing was not working in Jetty.
