### ISSUE TITLE
Facets. Make it possible to open new tab in browser when CTRL+clicking or Right click>"open link in new tab/window" 

### ISSUE THREAD

**Issue by Klindten** [netarchivesuite/solrwayback#404]
When CTRL+clicking (or Right click  "open link in new tab/window" under the facets you navigate to the linked page instead of opening a new tab. 

In some cases it´s great to start loading multiple results under facets using tabs,

**Comment by jorntx** [comment]
Totally unrelated but I personally like the issue number assigned to this ticket:))

**Comment by Klindten** [comment]
I always use CTRL+click and no right-click. So for me it´s fine. Maybe this trick can be a part of the updated guide i do later this year.

**Comment by Klindten** [comment]
Except facets this CTRL+Click could also be handy for the Tools like "visualize search results" etc.). Off course yiou can always open new windows in advance. But this is a different user experience than doing waht you are used to (opening many tabs).
