### ISSUE TITLE
All unit tests should use the test configs

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#409]
Some of the unit tests in SolrWayback calls
```
PropertiesLoader.initProperties()`
```
upon start. This makes the code look for property files in the user's home folder. Instead they should use something like 
```
PropertiesLoader.initProperties(UnitTestUtils.getFile("properties/solrwayback.properties").getPath());
```
which makes the test use the test configs.

**Comment by thomasegense** [comment]
I find this important, so self assigning this for a fast fix.
