### ISSUE TITLE
Provide hints to the query

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#41]
When an error-prone query is issued, the front-end could provide feedback with suggestions. This could be implemented as-you-type as such detection is trivial. Examples of error-prone queries:

- `“That’s a ‘magic’ sock.”` ([Smart quotes](https://practicaltypography.com/straight-and-curly-quotes.html - suggest using straight `"` quotes)
- `foo and bar` (Non-capitalized booleans)
- `foo AND bar OR zoom` (ambiguous boolean logic - suggest using parentheses)
- `http://example.com/foo/bar` (single URL search in plain search mode - suggest using the specialised URL search mode)

**Comment by thomasegense** [comment]
Already covered in search guidelines help .

**Comment by tokee** [comment]
I think you should ask an experienced user interface designer about whether a guide has the same impact as context-sensitive help or not 😀.

**Comment by jorntx** [comment]
A guide has no way near the same impact as context-sensitive help. I see where @thomasegense is coming from with the query parser from hell but @tokee's suggestion could be a fine middle road where we provide hints as the user types and we detect something error prone. We will do nothing to prevent the user from submitting the query as is so the feature will be subtle and non intrusive. I can't promise that this won't end in a Javascript query parser from hell:)

**Comment by thomasegense** [comment]
It has to be as lightweight as possible. So I can accept a javascript function that does some elementary string logic and can 
return an (english) message if some query problems  is detected..  (I18N will be handled much later anyway.)

Seems @tokee  has appointed himself to writing a vanilla javascript function that takes the query as input. It can then be
refactored by the frontenders :)

**Comment by tokee** [comment]
The JavaScript at https://jsfiddle.net/Lhr16vn7/82/ checks

 * AND + OR without parentheses
 * lowercase and/or/not
 * ‟Smart quotes”
 * More:that:1_colon_without_quotes
 * URL search
 * Single-star (`*`)-search

The result is returned as an array of tuples, each tuple containing `[The problem, how to do it properly, suggestion for new query]`.

Ping to @jorntx & @jesperlauridsen who will undoubtedly swoon over my elegant JavaScript.

**Comment by jorntx** [comment]
Very nice work @tokee 🎉  We will certainly have a look at this and get it into play in the app.

**Comment by jorntx** [comment]
And yes we swooned and there is some nice regex action. Couldn't get the fiddle to work though guess that is some kind of browser issue.

**Comment by thomasegense** [comment]
Only thing I could find was missing checking for ( ) occurs the same number of times. I know this also require omitting those in phrase search. Same for quotes "

**Comment by tokee** [comment]
@jorntx for some reasom you have to press "Run" in the JSFiddle to get it to work.

@thomasegense yeah, handling things like unbalanced parentheses require something resembling a "real" parser. Not the thing I'll do for a first version. Unbalanced quotes might be easier as start and end is the same char.

**Comment by thomasegense** [comment]
@toes Yeah, do not want to go there again :) 
Fiddle is working fine for me and like the instant feedback idea.

**Comment by tokee** [comment]
Okay, here's a version that does the balancing quotes thing: https://jsfiddle.net/bsc6zkxy/12/

**Comment by thomasegense** [comment]
Seems to work also and handles escaped quotes.
Of course users should be able to search even though there is a parse warning.

**Comment by tokee** [comment]
Regexps are a drug: Check for balanced parentheses with quote support at https://jsfiddle.net/fa4pxg1s/25/

**Comment by thomasegense** [comment]
This has been  implemented in the the 4.0.5 version.
