### ISSUE TITLE
The logo should be easier to change

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#413]
Changing the logo shown in SolrWayback is currently possible in two ways:

1. Replace the file `kb_logo_desktop_blue.svg` in the SolrWayback WAR (or in the unpacked WAR under Tomcat)
2. Adjust `top.left.logo.image=/kb_logo_desktop_blue.svg` to another HTTP(S) URL
 
It would be a lot easier if a local file path could be used for the logo. Implementation wise it could be done by having the SolrWayback service pick up the property and expose the file through an endpoint.

**Comment by thomasegense** [comment]
It is already working exactly this way. The comment in the property-file is not more clear.
