### ISSUE TITLE
Solr start timeouts with no connection to port 8983

### ISSUE THREAD

**Issue by cslr** [netarchivesuite/solrwayback#424]
Hi

I'm using Debian Linux and solrwayback version 4.4.2

./bin/solr start

"Waiting up to 180 seconds to see Solr running on port 8983" timeouts.

Is there logs for solr somewhere (apache tomcat seem to open correctly according to logs)?

**Comment by VictorHarbo** [comment]
You could try running solr in the foreground with `./bin/solr start -f`

Does this show any errors?

**Comment by thomasegense** [comment]
@cslr  Also the solr logs are in /solrwayback_package_4.4.2/solr-7.7.3/server/logs
The SolrWayback  logs are in /solrwayback_package_4.4.2/apache-tomcat-8.5.60/logs
