### ISSUE TITLE
SolrWayback build fails on Linux

### ISSUE THREAD

**Issue by cslr** [netarchivesuite/solrwayback#428]
**mvn package command fails on error:**

Failed tests:   timeProximity(dk.kb.netarchivesuite.solrwayback.solr.SolrGenericStreamingTest): The returned crawl_date should be the nearest expected:<Fri Mar 15 1[3:31:51 C]ET 2019> but was:<Fri Mar 15 1[4:31:51 E]ET 2019>.

**uname -a** 

Linux nin 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

**java -version**

openjdk version "11.0.20" 2023-07-18

**Comment by thomasegense** [comment]
Hi @cslr 

It can build on Github(some virtual linux)+Ubuntu+Windows. I just tested master. I think there is some OS setting with default time that are causing this. I will see tomorrow if the unittest can be changed.  However I do not have access  to a Debian OS.

Just build with:
**`mvn package -DskipTests`**

**Comment by cslr** [comment]
> Hi @cslr
> 
> It can build on Github(some virtual linux)+Ubuntu+Windows. I just tested master. I think there is some OS setting with default timezone that is causing this. I will see tomorrow if the unittest can be changed. However I do not have access to a Debian OS.
> 
> Just build with: **`mvn package -DskipTests`**

Ok Thanks.

**Comment by thomasegense** [comment]
@cslr 
I have comitted a fixed to that unittest on master. Can you confirm it works? (and close the issue)

@tokee  Error was casting a field from Solr to Date. ( (Date)  doc.get("crawl_time")). That will use OS time.
 For comparison we have to use the Solr UTC format for comparison.
See changes in SolrGenericStreamingTest on master.

**Comment by white-gecko** [comment]
For me, the tests don't fail on Linux with jre11 (but with jre17, which is another issue).

**Comment by thomasegense** [comment]
I am closing this.
The original issue was fixed.
