### ISSUE TITLE
Url_search, disable checkbox should not also add 'http://' to URL

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#429]
Minor issue.

Click listener on url-search should only add http:// when it is enabled, not when it is disabled.

1) Click url search. (http://   added correct)
2) Make a search.
3) Clear field (you do not want another url search)
4) uncheck url-search. **http:// is added**   <- This is the error

**Comment by jesperlauridsen** [comment]
This has been fixed, and merged to main. Closing issue.
