### ISSUE TITLE
SolrWayback 3.2 software bundle

### ISSUE THREAD

**Issue by Fernando-Melo** [netarchivesuite/solrwayback#43]
SolrWayback 3.2 software bundle is working with java 8 but not with java 11

**Comment by thomasegense** [comment]
Thank you, it is known and I will update the install document in the next release which will be
later this year. Is it during the indexing that the error happens? The warc-indexer project is bound to java 8 for quite some time unfortunately.
But a quick fix can maybe be just to add something like this so the index command:
java    --add-modules java.xml.ws.annotation .... (maybe more)
It is in the batch_warc_folder.sh where you can add this to the java command. 
see: https://blog.codefx.org/java/five-command-line-options-hack-java-module-system/
(Notice I have not tried this myself)

**Comment by Fernando-Melo** [comment]
Yes, it was during the indexing. 
Like you said there were modules missing.
I changed to java 8 and it worked fine.
Maybe on the project documentation instead of JDK 1.8+ advise people to use JDK 1.8

**Comment by thomasegense** [comment]
fixed
