### ISSUE TITLE
Auto-normalise url_norm searches

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#44]
If the user makes a qualified query `url_norm:http://example.com/FOO`, `url_norm:"http://example.com/FOO"` or `url_norm:("http://example.com/FOO" OR "http://example.com/BAR")` etc, SolrWayback should rewrite the query using the `webarchive_discovery`-normaliser, as it does when the user explicitly selected "URL Search".

**Comment by thomasegense** [comment]
Newfrontend branch has a new search option for url search.
User enters an URL (must start with http:// or https://). The frontend then calls a service method that does
both puny encoding of domain + url normalize.

The returned normalized url then initiates a search:
url_norm:<value from service>
