### ISSUE TITLE
Cannot run solr-9 on Mac with M1 Pro

### ISSUE THREAD

**Issue by joncto** [netarchivesuite/solrwayback#444]
I run into problems when trying to run solr9, and I never get to see Solr running on port 8983.

Can it be related to the fact that I use a MacBook Pro 2021 with a M1 Pro prosessor? (Seems like Apple's Mx-processors are only supported by JDK17+ ).

If so, is there a workaround? (I got help to hack around this problem with SolrWB 4.4.2)
Or a possibility that SolrWB in the future will support Java 17?

This is the dialogue in my CLI:
```
(base) user@machine solrwayback_package_5.0.0 % solr-9/bin/solr start -c -m 4g
*** [WARN] *** Your open file limit is currently 256.  
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
*** [WARN] ***  Your Max Processes Limit is currently 4000. 
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Java 20 detected. Enabled workaround for SOLR-16463
Java 20 detected. Incubating Panama Vector APIs have been enabled
Waiting up to 180 seconds to see Solr running on port 8983 [-]  Still not seeing Solr listening on 8983 after 180 seconds!
```

**Comment by thomasegense** [comment]
You are running java20 and not java17. There is no support for java20 yet. Tomcat will also have a problem with java20.
 
Java17 should work, but have not been tested on MAC.

Can you try java17?

The log snippet does not show any error. The files are normal except for the java20 part.
To see what is happening in solr,  you have to open solr.log in the solr folder under logs.

**Comment by joncto** [comment]
I am so sorry for missing that oversight - downgraded to Java 17, and solr9 is working very well!

**Comment by joncto** [comment]
I am so sorry for missing that oversight - downgraded to Java 17, and solr9 is working very well!
