### ISSUE TITLE
Properties files must be in home directory on macOS

### ISSUE THREAD

**Issue by ulrichhave** [netarchivesuite/solrwayback#445]
In macOS it is a requirement that the two property files are located in the user's home folder in order for SolrWayback to work.

This should be pointed out in section 1 of the instructions "Initial Setup". Currently it is ambiguous.

Tested with Bundle version 5.0.0 on macOS in January 2024.

**Comment by thomasegense** [comment]
Correct, there is missing information about defining the new location in tomcat context parameter, if the properties are not in the home folder.

**Comment by thomasegense** [comment]
Documentation will be added next release. Also an empty tomcat-context file will be added.

If you want to test and place the two property files somewhere else,
then add this to a file called solrwayback.xml and place it it the folder: /tomcat-9/conf/Catalina/localhost/
You can then incomment the two environment variables and change location of propertyfiles.
(this file will will be included in next release in that tomcat folder)


<Context override="true">


</Context>

**Comment by thomasegense** [comment]
Added the README.md in the 5.1.1 release
