### ISSUE TITLE
Danish Stopwords are not UTF-8 encoded

### ISSUE THREAD

**Issue by white-gecko** [netarchivesuite/solrwayback#454]
The encoding of the Danish stop words some how broken. I assume, you know which would be the right words.

https://github.com/netarchivesuite/solrwayback/blob/7c9b2ffb03f25ba4cd9d6cc8d8b8895f5d2dac3b/src/bundle/properties/solrwaybackweb.properties#L85-L86

**Comment by thomasegense** [comment]
You are correct.  I checked our production environment and they are correct there.
I have fixed them in the project. 
Closing this.
