### ISSUE TITLE
The class SolrGenericStreaming is an empty java file

### ISSUE THREAD

**Issue by VictorHarbo** [netarchivesuite/solrwayback#461]
I am trying to resurrect my old memento branch, however merging from master makes the class `SolrGenericStreaming` turn empty. Is this because it shouldn't be used any more? @thomasegense

**Comment by thomasegense** [comment]
Correct. I was not aware of this. File should be deleted. It seems it was a merge by Toke that left the empty file when he rewrite all streaming logic.

**Comment by VictorHarbo** [comment]
Yes. The PR at #441 gives a great overview of what have been changed. I'll close this issue.
