### ISSUE TITLE
Add download-button/link for Ngram-CSV

### ISSUE THREAD

**Issue by Klindten** [netarchivesuite/solrwayback#463]
There used to be a download-button for Ngram search results.

Instead of correcting the q-parameter to force download - make a download - button/link.
[https://solrwb.kb.dk:4000/solrwayback/services/frontend/smurf/text/?q="thomas](https://solrwb.kb.dk:4000/solrwayback/services/frontend/smurf/text/?q=%22thomas) egense"&startdate=1998-01-01&enddate=2025-01-01&scale=YEAR

**Comment by thomasegense** [comment]
@Klindten  You can test at: https://solrwb-test.kb.dk:4000/solrwayback/
