### ISSUE TITLE
Reduce fields on playback

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#56]
`HtmlParserUrlRewriter.replaceLinks(ArcEntry arc)` uses `NativeSolrClient.findNearestHarvestTimeForMultipleUrls`, which indirectly calls `findNearestDocuments` which requests the fields defined in `indexDocFieldList`, which are `[id, score, title, url, url_norm, links_images, source_file_path, source_file, source_file_offset, domain,resourcename, content_type, content_type_full, content_type_norm, hash, type, crawl_date, content_encoding, exif_location, status_code, last_modified, redirect_to_norm]`.

Only `[url_norm, url, source_file, source_file_offset]` are used for rewriting. This means a lot of unused fields are retrieved from Solr, which adds up when the number of linked resources grows. The list should be trimmed to the 4 fields used.

**Comment by thomasegense** [comment]
Fixed.  (crawlDate was also required.)
Made a similar object as IndexDoc called IndexDocShort which only loads these 5 fields.
