### ISSUE TITLE
The geo-display should have better support for multiple record at exact same location

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#6]
The experimental Jodel-support means that there can be hundreds or thousands of documents with the _exact_ same coordinates. Some sort signalling, such as a blob with the hit count, should be introduced, with support for visually expanding the content markers.

**Comment by thomasegense** [comment]
@vitezg
This feature now has to be made in OpenStreetmap since we are dropping Google Maps.

**Comment by tokee** [comment]
Extremely slick! Thank you!
