### ISSUE TITLE
Cache heavy queries

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#63]
Some very heavy queries, such as `*:*` with facets, are also very usable. We should cache those and for once cache invalidation is not a hard problem: Simply perform a light search for the same `q` and `fq`, but with `facets=false rows=0 groups=false stats=false` and check if the number of hits matches what is cached.

**Comment by thomasegense** [comment]
Fixed. Caching can be configured in solrwayback.properties  with the new properties
#Solr caching. Will be default false if not defined
solr.server.caching=true
solr.server.caching.max.entries=1000
solr.server.caching.age.seconds=86400
