### ISSUE TITLE
Values should be quotes when using faceted filtering

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#7]
Showing the `type` facet with Twitter or Jodel datasets produced values containing spaces. Clicking on one of those results in 0 hits as the values are not quoted, leading to a filter query such as `type:Twitter Tweet` where the correct filter would be `type:"Twitter Tweet"`.

**Comment by thomasegense** [comment]
Fixed by Niels. Fix included in the 3.1 release.
