### ISSUE TITLE
Jodel rendering should collapse multiple harvests of the same thread

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#8]
Currently the renderer shows each harvest of the same thread as separate entities. Treating them as different representations of the same entity over time allows for features such as vote graphs for both post & comment as well as flags for deleted (triggered by sufficiently down voting or explicit deletes) comments as well as deleted posts.

**Comment by thomasegense** [comment]
All jodel support currently stand by since it is not possible to consistent harvest jodel anymore.
