### ISSUE TITLE
Create generic time-count (aka trend) support

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#9]
Visualization of trends, such as [Google Trends](https://trends.google.com/trends/explore?q=wayback), can be done for a lot of elements in SolrWayback. Some elements, such as phrases or MIME-types, are often viewed in number of `instances`. Other elements, such as file size or image pixel count, can be viewed as `sum`, `mean` or `average` of the numbers. Fortunately those 4 metrics are easily retrievable using Solr.

The problem is normalisation. Basic normalisation is, e.g. by using all elements as opposed to the selected ones, is simple. Ignoring duplicate entries or entries with the same URL is harder - maybe [field collapsing](https://lucene.apache.org/solr/guide/7_2/collapse-and-expand-results.html) works together with the [Stats Component](https://lucene.apache.org/solr/guide/7_2/the-stats-component.html)?

**Comment by thomasegense** [comment]
Smurf-compontent (without query restrictions) to be included in SolrWayback frontend. This covers the "google trends" part of the jira.
As for the other metrics there is a toolbox with various visualizations and more can be added later.

**Comment by thomasegense** [comment]
Smurf-compontent created as internal jira in the frontened project.
